plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mrumi.dnd5edicelab'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mrumi.dnd5edicelab'
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName '1.5.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
