plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mrumi.apologeticasteroid'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mrumi.apologeticasteroid'
        minSdk 26
        targetSdk 35
        versionCode 22
        versionName '0.22.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}